### ISSUE TITLE
Support for custom color palettes?

### ISSUE THREAD

**Issue by quicknir** [mihnita/ansi-econsole#13]
Is there any way to do this?

**Comment by mihnita** [comment]
There is no way to do it now, without code changes
But nice idea :-)

If you want to tinker with it, the palettes and the palette selection are here:
    src/mnita/ansiconsole/utils/AnsiConsoleColorPalette.java

The UI for selecting the palette is here:
    src/mnita/ansiconsole/preferences/AnsiConsolePreferencePage.java

I think the tricky part would be the UI.
A whole new dialog to define a palette, and way to import / export palettes, and supporting more than one custom palette, maybe giving them names...

So a full solution will require a bit of work :-)

**Comment by mihnita** [comment]
I looked at what it takes, and there is a lot of complexity for relatively little benefit.
Would need a special GUI editor for 16 colors, and then a way to manage the custom palettes (list / add / remove / edit).

It currently supports 8 predefined palettes, I can add more on demand.

So I've decided not to implement custom palettes, sorry.
