### ISSUE TITLE
Output not filtered properly

### ISSUE THREAD

**Issue by heftig** [mihnita/ansi-econsole#14]
I've tried using this to display colored output from GCC, but ran into two bugs:

- The escape characters that precede each control sequence are still displayed as a box containing hex numbers.
- The `[K` sequence (erase end of line) is not supported and remains visible.

Eclipse 4.5.0, Linux.

**Comment by paulvi** [comment]
Could you give full output, and how to reproduce it

**Comment by mihnita** [comment]
It's OK, I know what the problem is.
I have a fix, I will try a release over the week-end.
Thank you very much,
Mihai
