### ISSUE TITLE
Support full (ansi?) input on Eclipse console

### ISSUE THREAD

**Issue by cschneider** [mihnita/ansi-econsole#23]
I am using jline and the Apache karaf console a lot. When I start karaf from a linux terminal I have all the features like history, inline editing, completion. These work by using the tab and cursor keys. 
I think these are ansi key sequences but I am not sure. 

The big problem in eclipse is that in the console all these special keys do not seem to get forwarded to my application. So all the nice features of jline and the karaf shell are lost.

Would it be possible in a similar way as to display the ansi sequences also be possible to forward the keys? If this is the wrong place to add this then I would be very happy about any pointers to where to ask this.

Christian

**Comment by paulvi** [comment]
As I know ansi-econsole is hooks i Eclipse Console View to display right.
Dealing with input would be something completely new.

Waiting for @mihnita

**Comment by mihnita** [comment]
This plugin installs a callback in the standard Eclipse console, and that is not a full console.
The callback is something like "this is the output line, add style info to it"
So there is not much that can be done there. Can't change the text, can't affect other lines of text.

It might be possible to write a console from scratch, but then it is not going to be the standard Eclipse one, so the application's standard output will not go there.

For a full terminal you might try something like this:
   https://marketplace.eclipse.org/content/tm-terminal
   https://marketplace.eclipse.org/content/terminal-plug

**Comment by paulvi** [comment]
@cschneider Take a look also at http://marketplace.eclipse.org/content/tm-terminal

and an example of it's extention https://github.com/angelozerr/angular2-eclipse/wiki/ngTerminal
