### ISSUE TITLE
Cursor movements

### ISSUE THREAD

**Issue by paulvi** [mihnita/ansi-econsole#24]
Is it feasible to support cursor movement? see https://github.com/de-jcup/egradle/issues/107#issuecomment-254959205

**Comment by mihnita** [comment]
It is not possible (from all I know) to implement cursor movement in the standard Eclipse console.
All I can get there is a callback for each line asking me to return a bunch of offsets + attributes.
There is no way to touch other lines, or even the current one. All you can do is color it.

It might be possible to write a full console replacement (and there are at least 2 I know of).
But I  don't know of any way to replace the standard console with your own.
Which means they will not be used as standard / error output from applications.

**Comment by paulvi** [comment]
What console replacement can you recall?
