### ISSUE TITLE
Can't use the update site

### ISSUE THREAD

**Issue by cgrand** [mihnita/ansi-econsole#25]
I tried variations of `https://www.mihai-nita.net/eclipse` to no avail. What is the current update site?

**Comment by paulvi** [comment]
Try again later or use www.nodeclipse.org/updates/

**Comment by cgrand** [comment]
Thanks Paul! http://www.mihai-nita.net/eclipse has been failing for days so nodeclipse is the solution.

**Comment by paulvi** [comment]
It is not the latest though

**Comment by paulvi** [comment]
It is also bundled into STS, so update for STS should also have it

**Comment by mihnita** [comment]
I have tried https://www.mihai-nita.net/eclipse (both http and https), and works.
Updates did not fail, and then I've uninstalled the plugin and installed it again, from the site.
It is not 100% impossible that the hosting had some problems.

There is one think though that I think is an Eclipse problem, and I was bitten before by it...
There is a checkbox (bottom-left of the dialog) saying "Grouped by category"
When that is checked, no plugin shows up.
When unchecked you can see both the "Ansi Console" plugin, and the "External Filter" one.
For a long time "External Filter"  was not there, so "Ansi Console" was always visible, checkbox or not.

Please let me know if things are also OK on your side...

Maybe this week-end, or during the holidays, I will try to figure out an alternate place, just in case it happens again.
Everything needed to build things is already on Github, but it is convenient to be able to just install it.

It looks like Github has now the option to have a small static website served by github, with the files pushed from git.
So I will try to figure out how to do it.

And maybe automate things more... I would like to be able to just git clone, run maven or groovy, and generate everything, even the files for the website, then git push :-)

**Comment by cgrand** [comment]
The problem originally shew up in the CI of [CCW](http://ccw-ide.org/). I tried the update site from eclipse and then with curl. All failed. Right after reading your post, I tried again with curl (on https://www.mihai-nita.net/eclipse/site.xml) and it works (yesterday I was redirected a couple of time before ending on a 404). Thanks!

**Comment by mihnita** [comment]
Unfortunately I can't tell what the problem was.
I did no changes with the side in any way. I suspect an ISP "glitch"

So I will put together a way to serve this from an alternate location.
Probably even GitHub, now, that you can create and static serve a mini-website.

**Comment by tymekg** [comment]
FYI, the issue still occurs.
This is the exact error I get:
```
Unable to read repository at http://www.mihai-nita.net/eclipse/content.xml.
Received fatal alert: internal_error
```
I'm using Eclipse Neon, particularly:
```
Eclipse for JavaScript and Web Developers

Version: Neon.1a Release (4.6.1)
Build id: 20161007-1200
```
Installing from Nodeclipse  site worked well.

**Comment by mihnita** [comment]
I have mirrored everything on GitHub, you should be able to install it from here:
   http://mihnita.github.io/ansi-econsole/install

It is a 100% identical copy of the stuff on my site, and I installed it myself to make sure it works.

I am on
```
  Eclipse Java EE IDE for Web Developers.
  Version: Neon.1 Release (4.6.1)
  Build id: 20160913-0900
```

**Comment by mihnita** [comment]
Sorry for the troubles, I can't see anything suspicious, I don't know what is going on...
I am going through the ISPs logs now, to see if there is something suspicious there...
Thanks for the patience.

**Comment by schoeppe** [comment]
I had the same issues installing it from http://www.mihai-nita.net/eclipse this morning, but using your GitHub-Mirror http://mihnita.github.io/ansi-econsole/install did the job!
Thank you for your work!

**Comment by borisivan** [comment]
As of right now, neither site listed in the comment above work. Redirects resolve to 404s from both sites.
