### ISSUE TITLE
doesn't work on macOS High Sierra

### ISSUE THREAD

**Issue by martinlippert** [mihnita/ansi-econsole#30]
users of STS report that this doesn't work on the just released macOS High Sierra. The output shows up as blank, although the characters are there.

See also:
https://github.com/spring-projects/spring-ide/issues/196

**Comment by mihnita** [comment]
Unfortunately I don't have a machine that I can update to High Sierra.
I will find someone who has one that I can use.

I can think of some experiments meantime...

1. For instance print to stderr
In Java System.err.println("This should go to stderr");
That should be red. Is it?

2. Install Grep Console
https://marketplace.eclipse.org/content/grep-console
Does it work?

3. I can put together a really minimal plugin that writes a colored "this is RED GREEN BLUE text"
to the console and see if that works.
Bypassing all the escape interpretation and all.

====

I  highly suspect there is nothing wrong with the plugin though, but with the OS itself ()

**Comment by paulvi** [comment]
In https://github.com/spring-projects/spring-ide/issues/196#issuecomment-333129640 it is linked to Eclipse SWT issue https://bugs.eclipse.org/bugs/show_bug.cgi?id=525383

**Comment by jgangemi** [comment]
if i turn on showing the escape sequences in the preferences, the log lines start rendering again.

**Comment by mihnita** [comment]
Meantime I've updated to High Sierra and checked, it is all good.
