### ISSUE TITLE
Install via Eclipse Marketplace fails with 302 (but the update site works)

### ISSUE THREAD

**Issue by sorin-costea** [mihnita/ansi-econsole#33]
eclipse.buildId=4.7.2.M20171130-0510
java.version=1.8.0_152
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product

org.eclipse.equinox.p2.transport.ecf
Error
Tue May 22 14:37:35 CEST 2018
HTTP Server Unknown HTTP Response Code (302):http://www.mihai-nita.net/eclipse/content.xml

org.eclipse.ecf.filetransfer.BrowseFileTransferException: General connection error with response code=302 and header(0)=HTTP/1.1 302 Found
	at org.eclipse.ecf.provider.filetransfer.browse.URLFileSystemBrowser.runRequest(URLFileSystemBrowser.java:134)
	at org.eclipse.ecf.provider.filetransfer.browse.AbstractFileSystemBrowser$DirectoryJob.run(AbstractFileSystemBrowser.java:69)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)

**Comment by nickheniser** [comment]
I have the same exact issue, but I can't get update site to work either.

http://www.mihai-nita.net/eclipse
