### ISSUE TITLE
set TERM enviroment 

### ISSUE THREAD

**Issue by Zardoz89** [mihnita/ansi-econsole#34]
It would be nice if ANSI console has a option to setup a environment var TERM with something.

I have my colour appender for log4j that uses TERM to detect if the console output accepts ANSI escape sequences, and would be nice if I don't need to setup it manually for every project.

**Comment by mihnita** [comment]
That might be nice, indeed. I will give it a try!

**Comment by mihnita** [comment]
Unfortunately too messy do do...

There is no official way to change the environment for a running Java application, you can only set it at launch time.
So this plugin would have to be a Launcher for that.
But it feels too intrusive to make it a Launcher only for this feature.

You can set the TERM environment in the launcher (Run Configurations -- your configuration -- the Environment tab).

Also, it looks like for me the application inherits the environment I have when I start Eclipse.

**Comment by Zardoz89** [comment]
Since I installed Eclipse Photon on my Kubuntu, looks that isn't necessary to setup a TERM environment. Looks that Eclipse it's receiving a TERM environment var and the apps are inheriting.
On any case, thanks!
