### ISSUE TITLE
Can not install on eclipse 2018-09, 302 error from update site

### ISSUE THREAD

**Issue by nickheniser** [mihnita/ansi-econsole#39]
I am trying to install from behind a corporate firewall and i get a 302 http error when trying to install via the marketplace and manually via the update site URL: http://www.mihai-nita.net/eclipse

I am using eclipse 2018-09, and I can install other plugins just fine.  This is the only one that is giving me trouble.

This is possibly related to #33.

**Comment by mihnita** [comment]
I've spent some time on this capturing network packets and tweaking things.

So I think I have managed to eliminate all redirections (302 is URL redirection).
The only redirect was from the http to the https version of my site (hosting the plugin), but I think I've managed to eliminate it.

Please let me know if this solves the problem.

Thank you!
Mihai

**Comment by nickheniser** [comment]
Just tried again behind my corporate proxy and it works!  Thanks!

**Comment by mihnita** [comment]
Thank you for confirmation :-)
