### ISSUE TITLE
Ansi Console doesn't recognize GCC color escape sequences

### ISSUE THREAD

**Issue by intractabilis** [mihnita/ansi-econsole#48]
GCC accurately issues the color escape sequences, I can see colors in the terminal, but Ansi Console ignores the escapes. I attached buildlog.txt with the contents of the Eclipse console and two screenshots how it looks like in Eclipse and in a terminal.

[buildlog.txt](https://github.com/mihnita/ansi-econsole/files/4176559/buildlog.txt)

![new-239](https://user-images.githubusercontent.com/45959195/74098132-484b5580-4ac9-11ea-844f-3406a0fc1595.png)
![new-240](https://user-images.githubusercontent.com/45959195/74098159-a4ae7500-4ac9-11ea-86ac-de94982bc4d1.png)

**Comment by mihnita** [comment]
Should be fixed now. Thanks.

**Comment by intractabilis** [comment]
It works!
