### ISSUE TITLE
Plugin Broken with Eclipse 2020.09 and Ubuntu 18.04

### ISSUE THREAD

**Issue by gbonneau-hardent** [mihnita/ansi-econsole#54]
I tried with Eclipse Version: 2020-09 (4.17.0), Build id: 20200910-1200 the plugin. After installation I ran the testing application AnsiConTest. The console output doesn't yield any colors. I got <<<>>>.  If I copy and paste the content of the debug/run console the characters are:

<<<[;H[;f[;0H[;0f[;1H[;1f[;4H[;4f[;42H[;42f[0;H[0;f[0;0H[0;0f[0;1H[0;1f[0;4H[0;4f[0;42H[0;42f[1;H[1;f[1;0H[1;0f[1;1H[1;1f[1;4H[1;4f[1;42H[1;42f[4;H[4;f[4;0H[4;0f[4;1H[4;1f[4;4H[4;4f[4;42H[4;42f[42;H[42;f[42;0H[42;0f[42;1H[42;1f[42;4H[42;4f[42;42H[42;42f>>>

**Comment by mihnita** [comment]
This is as expected, and I don't think it behaved differently in other Eclipse versions.
If it did, it was a bug, and I would like to learn about it.

All the sequences used are either of type `H` ("Cursor Position") or `f` ("Horizontal Vertical Position")
https://en.wikipedia.org/wiki/ANSI_escape_code#Terminal_output_sequences

This never worked.

The only sequences that trigger color changes are the ones ending in `m` ("Select Graphic Rendition")
See https://en.wikipedia.org/wiki/ANSI_escape_code#SGR

**Comment by mihnita** [comment]
The test in `AnsiConTest` that produces that sequence is `testCursorMovementConsumed`
And it does as expected: "consumes" cursor movement escape sequences, leaving only the `<<<>>>` visible.

To see colors you can un-comment the other tests:
```
        // allTestScrolling();
        // allKindOfTests();
        // allTest256();
```
