### ISSUE TITLE
Use a toggle button instead of a push button for enable/disable

### ISSUE THREAD

**Issue by laeubi** [mihnita/ansi-econsole#57]
Currently one needs to decide from the icon if the action is enabled/disabled.

It would be much better if the button uses a toggle button.

**Comment by mihnita** [comment]
I kind of have something in the works.
It uses the standard Eclipse enable / disable, which also fixes https://github.com/mihnita/ansi-econsole/issues/45.
And uses commands, better than the current approach (you can see them, assign hot-keys, etc.)
Cleaner than my old way of doing things.

But what I don't like about it is that I don't have control over the button image anymore.
It only allows for one image, and Eclipse algorithmically creates a "disabled" version.
That looks OK-is on Mac and Linux, but on Windows-dark mode is looks almost the same as the enabled one.
Really hard to distinguish.

I probably have to try it again with Eclipse 2020-12. They keep improving the dark support.

See the `move_to_commands_working` branch, if curious.

**Comment by mihnita** [comment]
Implemented and released.
