### ISSUE TITLE
Not working on eclipse kepler

### ISSUE THREAD

**Issue by cindrmon** [mihnita/ansi-econsole#67]
Good day!

It seems like this plugin doesn't work on eclipse kepler.

The reason why I wanted it on this specific release of eclipse kepler is that my teacher still uses this for teaching java, and I wanted my programs to work for him as well. I'm testing it out currently, and it seems to not work.

This is the eclipse install:
```
Eclipse Java EE IDE for Web Developers.

Version: Kepler Release
Build id: 20130614-0229
```
Eclipse kepler link [here](https://www.eclipse.org/downloads/packages/release/kepler/r/eclipse-ide-java-ee-developers)

Sorry for using this version of eclipse.

**Comment by mihnita** [comment]
Sorry, but that is "ancient" (2013).
I am sorry, but I can't support it anymore, Eclipse deprecated things and "forced" my to migrate to newer APIs.

I know it is not your fault either, can't force your teacher to change his ways.

But try version 1.3.5 of my plugin, I tested it and works.

First, uninstall the version installed from the Eclipse Marketplace (if installed):
* "Help" -- "About Eclipse" -- "Installation Details"
* Select "Ansi Console" and click "Uninstall..." -- "Finish"
* Restart

If you did not already installed the plugin from Marketplace, then you need to add the install site:
* "Help" -- "Install New Software…" and click "Add…"
* Add the following URL: http://www.mihai-nita.net/eclipse

Now you should be able to install older versions:
* "Help" -- "Install New Software…"
* In the "Work with:" drop-down select the site mihai-nita.net site

You should see "Ansi  Console" and "External Filter"

Un-check the "Show only the latest version of available software"

You should now see the version 1.3.5.201612301822 version of the plugin
Install it, it should work on Kepler.

**Comment by cindrmon** [comment]
Thank you for the tip! i'll try it out when i have the time.
