### ISSUE TITLE
Ansi Console catches CTRL+C

### ISSUE THREAD

**Issue by Davidius86** [mihnita/ansi-econsole#68]
The update to version 1.4.5.202111240049 catches the CTRL+C command on eclipse version 2019-06 (4.12.0). This makes this version unusable.

Adapting the key association in eclipse does not have any effect.

**Comment by bligny** [comment]
Same issue for me with latest very. Quite unusable anymore indeed :-(

**Comment by nils-christian** [comment]
Can confirm. This is a major blocker for me, as it basically destroys Copy&Paste.

**Comment by pascalheraud** [comment]
yes ! Please fix :)

**Comment by sebthom** [comment]
Got surprised by this too :-)

**Comment by elab** [comment]
See #65.

**Comment by mihnita** [comment]
Should be fixed (v1.4.5.202111252246) (Nov 25)
Apologies, and thanks for reporting it.

If anyone can confirm, I will close this.

**Comment by elab** [comment]
Thanks, Mihai! I can confirm for the v1.4.5.202111252246 that in my tests (Eclipse 2021-09, Windows 10):
- the copying from console and other views are not interfere anymore;
- in the console: Ctr+C / Ctrl+Ins copies without escapes (as desired), Ctrl+Alt+C / Ctrl+Alt+Ins copies with escapes (nice);
- "Copy text with escapes" button in the console toolbar copies with escapes (as stated).

The only remaining (minor) point is that - whereas console has the focus - the global menu "Edit > Copy" and the context menu "Copy" are copying with escapes.

**Comment by mihnita** [comment]
I've tried to intercept the menu & context menu Copy options.
But they seem to not go through the normal commands...
I don't know (yet) how to "intercept" them.

Created issue #69 to track it.

Thank you,
Mihai

**Comment by Davidius86** [comment]
Problem fixed
Thank you very much :)
