### ISSUE TITLE
Full support for terminal ProgressBar

### ISSUE THREAD

**Issue by guw** [mihnita/ansi-econsole#71]
I have been using https://github.com/ctongfei/progressbar in my CLI apps . The colors work pretty nicely. The thing that seems to be missing is the line reset.

In macOS Terminal the progress bar keeps updating a single line. In the Eclipse Console it's not updating the line but keep adding a new line. Perhaps this can be added to this plug-in if it's possible with the Eclipse Console view. There might be a limitation in the Eclipse Console, though.

**Comment by mihnita** [comment]
Unfortunately there is not much (if anything) that his plugin can do.

The hook that Eclipse offers (and this plugin uses) is basically "here is a line of text, give me back color ranges"
There is no way to modify the text, change cursor coordinates, clear screen / line, etc.
