### ISSUE TITLE
Parameter default values are not recognized

### ISSUE THREAD

**Issue by Paddjie** [mihnita/ansi-econsole#73]
Missing values between semicolons are ignored instead of being interpreted as 0, which is the default value according to the ECMA-48 standard.

 The escape sequence `"\33[38;2;;255;m"` ought to be the same as `"\33[38;2;0;255;0m"` for instance.

**Comment by mihnita** [comment]
Interesting, I didn't know this one.
I'll have to check the real behavior in a few (most popular?) terminals, and then decide what to do.
Depending on that it will be a global fix, or an option.
