### ISSUE TITLE
Color errors with Project -- Build All 

### ISSUE THREAD

**Issue by ydaveluy** [mihnita/ansi-econsole#78]
Dear Mihai,

When building multiple makefile project with project->Build all projects, colors in the console are not all the time correctly escaped.

To reproduce, create 3 or 4 makefile projects and replace the makefile content with:
`
Color_Off=\033[0m

Black=\033[0;30m
Red=\033[0;31m
Green=\033[0;32m
Yellow=\033[0;33m
Blue=\033[0;34m
Purple=\033[0;35m
Cyan=\033[0;36m
White=\033[0;37m

all:
	@echo -ne "normal $(Red)red"
	@echo -ne "\nred "
	@echo -ne "red$(Green) green"
	@echo -e "\ngreen$(Color_Off) normal"
	@echo -e "normal$(Yellow) yellow$(Blue)blue$(Color_Off)normal"
`
Can you reproduce this issue ?

Regards,

Yannick

**Comment by mihnita** [comment]
Sorry, no I can't.

Is this with the official release (from Marketplace)? Or the test one on my site?

If it is the marketplace one I suspect this is the same as issue #75

**Comment by mihnita** [comment]
Ah! 
Got it, reproduced.
I missed the "Build All" aspect.

**Comment by mihnita** [comment]
Note: sorry, i am kind of slow these days, I can probably only move things on week-ends
